### ISSUE TITLE
Visualization scale can be incorrect

### ISSUE THREAD

**Issue by bkmgit** [EmbroidePy/vpype-embroidery#4]
When visualizing a DST file, the scale seems to be incorrect. For example one can try:
```
 vpype begin grid -o 25 25 10 10 circle 0 0 100 end efill show
```
![Direct Show](https://user-images.githubusercontent.com/1679477/169270174-6b33a182-e434-46d9-bb20-e4ec206b189e.png)

And then
```
vpype begin grid -o 25 25 10 10 circle 0 0 100 end efill ewrite grid.dst
vpype eread grid.dst show
```
![Write DST Then Show](https://user-images.githubusercontent.com/1679477/169270225-d76a730d-bcfb-4857-82a9-c8ea4e1317ec.png)

Possibly https://github.com/EmbroidePy/vpype-embroidery/blob/main/vpype_embroidery/eread.py#L25 or https://github.com/EmbroidePy/vpype-embroidery/blob/main/vpype_embroidery/ewrite.py#L24 needs to be updated?

**Comment by tatarize** [comment]
Hm. This does seem like it must be accurate. Since that should convert forward and backwards correctly and it clearly doesn't. Unitless is 1/96th of an inch for vpype as it's equal to a common css pixel. And embroidery units are 2.645833333333333 (1/96th inch) per (1/10th mm). So 2.65 is the conversion factor from px to emb (embroidery units).

`ewrite` does p (px) * 2.65 converting. So we do px * px / emb giving us px squared divided by emb which is wrong.

`eread`  does lc.scaled(1.0/2.64) which then has emb scaled data appended which is in emb giving us emb * emb/px which is emb squared divided by px which *also* appears to be wrong.

Yes, I must conclude this appears to be entirely in error. If we cycle through this we will convert to `px*px * emb*emb / px * emb` or so. Rather than scaling back to 1.0 we'll be off by a quite large factor.

**Comment by tatarize** [comment]
Okay, double checked all the work, turns out it was mostly correct. It's scaling by 2.65x on load because the scale is applied before the points are added and doesn't take effect. That's not that bad. It means it's saving fine but the reload is a bit off. I'll give it better units and correct the error.

**Comment by tatarize** [comment]
https://github.com/EmbroidePy/vpype-embroidery/releases/tag/0.3.0

**Comment by bkmgit** [comment]
Thanks for the quick update. Seems fine now.
